### ISSUE TITLE
Plotregion function genome location doesn't match with the location in genome browser

### ISSUE THREAD

**Issue by ziyuanhe** [aifimmunology/MOCHA#138]
DAP was called at 'chr4:122617500-122617999' for IL21 
[preRA_tea_seq_cd4tna_peak_regions_preRAvsHealthy_IL21.pdf](https://github.com/aifimmunology/MOCHA/files/12114926/preRA_tea_seq_cd4tna_peak_regions_preRAvsHealthy_IL21.pdf)

https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr4%3A122616063%2D122619437&hgsid=1662213964_vJLpiUbpAj793cAuiVHmLvrjzIQQ

**Comment by markphillippebworth** [comment]
This is now fixed.
