### ISSUE TITLE
annotateTiles incorrectly errors error when we provide TxDb and Org with a RangedSummarizedExperiment 

### ISSUE THREAD

**Issue by imran-aifi** [aifimmunology/MOCHA#144]
Incorrectly throws an error when we provide TxDb and Org with a RangedSummarizedExperiment 
works:
```R
MOCHA::annotateTiles(
    Obj = mochaObj #RangedSummarizedExperiment 
)
```
errors:
```R
mochaObj <- MOCHA::annotateTiles(
    Obj = mochaObj
    TxDb = TxDb.Hsapiens.UCSC.hg38.refGene,
    Org = org.Hs.eg
)
```

Error: Invalid inputs. Verify Obj is a RangedSummarizedExperiment and tiles were called from an ArchR project. If Obj is a GRanges, TxDb and Org must be provided.

Input is valid, orgdb and txdb were simply unnecessary. Should still run.

**Comment by markphillippebworth** [comment]
Bug fixed [now](https://github.com/aifimmunology/MOCHA/commit/07ff55cfdb5d1a5a34c96146882bc5fd126e1ae5)
