### ISSUE TITLE
Clarify language in error in getPopFrags

### ISSUE THREAD

**Issue by imran-aifi** [aifimmunology/MOCHA#146]
Error message in this line refers to "cellSubsets", but the user does not see this parameter. 
Recommend renaming cellSubsets to cellPopulations.
https://github.com/aifimmunology/MOCHA/blob/65cb05959ef644389e09d75174c2951103fc67a6/R/getPopFrags.R#L57C39-L57C50

**Comment by markphillippebworth** [comment]
I've fixed it in [9c97042](https://github.com/aifimmunology/MOCHA/commit/9c97042fe182013fee65b22c777d6b9bdd603f4d)
