### ISSUE TITLE
"ALL" input to cellpopulations breaks

### ISSUE THREAD

**Issue by imran-aifi** [aifimmunology/MOCHA#156]
1) Remove earlier check for cellpopulations, 
https://github.com/aifimmunology/MOCHA/blob/98337d41a50da49045eeb5a7abef0cb1bed055ec/R/callOpenTiles.R#L369
as it is redundant with this check: https://github.com/aifimmunology/MOCHA/blob/ba16c80d6dd002416750879c60f026487fa9d223/R/callOpenTiles.R#L398

2) Make check for "ALL" case-insensitive with toLower

**Comment by markphillippebworth** [comment]
I think like 398 needs to come before line 369, so that it checks if ALL is set before it checks if all the cell types can be found within the metadata.

**Comment by markphillippebworth** [comment]
Issues should be fixed with recent merge into development.
