### ISSUE TITLE
plotRegion dimension error when plotting many groups

### ISSUE THREAD

**Issue by lokada-aifi** [aifimmunology/MOCHA#49]
Observed the following error when using `plotRegion()` on a grouped counts object (9 groups). Also observed in other datasets when plotting larger numbers of groups (MP).      
Call:  
`options(repr.plot.width =10, repr.plot.height = 5)`  
`scMACS::plotRegion(proj_counts2, motifSetName = 'Motifs', relativeHeights =c(Chr = 0.9, 'Normalized Counts' = 4, Links = 1.5, Genes = 2, AdditionalGRanges = 4.5))`

Error Message:  
`Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto), : Viewport has zero dimension(s)`

Fix:  
Was able to plot without error by increasing plot height dimensions (external to the plotting function) and/or modifying the relativeHeights argument to allocate more plotting space to the per-group normalized count plots (e.g. `relativeHeights = c(Chr = 0.9, 'Normalized Counts'=7, Genes = 2)`).  Note: excluding the motif labels (`motfiSetName = NULL`) also allowed the plot to render, but I still believe this to be a dimensions issue where the graph is not able to accommodate the additional data within the allocated space.  

With the default `plotRegion()` settings, this error will be more likely to occur in datasets that have a larger number of groups or possibly a larger number of extra tracks. Can we improve to mitigate errors and/or provide better guidance for users? Note that plot dimensions are dependent on user's graphics device settings, so it may be difficult to completely optimize formatting from with the function while maintaining the function's (intended) flexibility.

**Comment by markphillippebworth** [comment]
We've re-written how MOCHA handles plotting, so graphics are no longer handled by ggbio. This error should hopefully be resolved, and I'm closing it. Let me know if it occurs again.
