### ISSUE TITLE
parameters for scMACS::getDifferentialAccessibleTiles

### ISSUE THREAD

**Issue by ziyuanhe** [aifimmunology/MOCHA#71]
### Discussed in https://github.com/aifimmunology/MOCHA/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **ziyuanhe** October  3, 2022</sup>
Hey guys, I have been experimenting with the parameters in the getDifferentialAccessibleTiles functions. as explained to me by Samir, signalThreshold does appear to have a huge impact in the differential peaks detected. 
in CD4 naive (7 preRA vs 6 healthy), if all other parameters are the same and same peak sets.
- signalThreshold=15 generates  12535 peaks at FDR<0.2
- signalThreshold=14 generates  13571 peaks at FDR<0.2
- signalThreshold=13 generates  7206 peaks at FDR<0.2
- signalThreshold=12 (default) generates  3400 peaks at FDR<0.2
- signalThreshold=10 generates  0 peaks at FDR<0.2

if i understand this line correctly `idx <- which(medians_a > log2FC_filter | medians_b > log2FC_filter | diff0s >= minZeroDiff)`, 
signalThreshold filters out the peaks whose median are lower than this value in both groups. What about filter by logfc difference as in seurat in scRNA differential or you are worried about the smaller peaks being noisy?  even though higher threshold seems to give me more DAPs, my worries is that i will completely missing the smaller peaks which maybe on/off status. 

any insights of how to set this parameter based on the data?

Here is the underline peak matrix distribution for CD4 naive 
[preRA_tea_seq_cd4tna_mocha_peaks_cell_type_histogram.pdf](https://github.com/aifimmunology/MOCHA/files/9700852/preRA_tea_seq_cd4tna_mocha_peaks_cell_type_histogram.pdf)
</div>

**Comment by markphillippebworth** [comment]
We have now implemented an optimization protocol for determining the threshold, which will vary according to the number of cells /sequence depth (and thus the resulting noise level of low level peaks).
